server:
  port: 8088
  context-path: /MQ_WeTwitter

spring:
  application:
    name: MQ_WeTwitter
  transaction:
    default-timeout: 60 #Default transaction timeout in seconds.
  mvc:
    view:
      prefix: /WEB-INF/views
      #prefix: /templates/
      suffix: .jsp
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.15.177.118:3366/MQ_WeTwitter
      username: joshua
      password: "@njl123NJL"
      maximum-pool-size: 10
      minimum-idle: 5
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  rabbitmq:
    host: 127.0.0.1
    port: 5762
    username: guest
    password: guest
    publisher-confirms: true     #消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
    virtual-host: /
    


  
      
    
  
